//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentWcfConsume.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/testwcf")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string filField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string first_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idstudentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cin {
            get {
                return this.cinField;
            }
            set {
                if ((object.ReferenceEquals(this.cinField, value) != true)) {
                    this.cinField = value;
                    this.RaisePropertyChanged("cin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fil {
            get {
                return this.filField;
            }
            set {
                if ((object.ReferenceEquals(this.filField, value) != true)) {
                    this.filField = value;
                    this.RaisePropertyChanged("fil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idstudent {
            get {
                return this.idstudentField;
            }
            set {
                if ((this.idstudentField.Equals(value) != true)) {
                    this.idstudentField = value;
                    this.RaisePropertyChanged("idstudent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllStudents", ReplyAction="http://tempuri.org/IService1/GetAllStudentsResponse")]
        StudentWcfConsume.ServiceReference1.Student[] GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllStudents", ReplyAction="http://tempuri.org/IService1/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<StudentWcfConsume.ServiceReference1.Student[]> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateStudent", ReplyAction="http://tempuri.org/IService1/CreateStudentResponse")]
        void CreateStudent(StudentWcfConsume.ServiceReference1.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateStudent", ReplyAction="http://tempuri.org/IService1/CreateStudentResponse")]
        System.Threading.Tasks.Task CreateStudentAsync(StudentWcfConsume.ServiceReference1.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudent", ReplyAction="http://tempuri.org/IService1/UpdateStudentResponse")]
        void UpdateStudent(StudentWcfConsume.ServiceReference1.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStudent", ReplyAction="http://tempuri.org/IService1/UpdateStudentResponse")]
        System.Threading.Tasks.Task UpdateStudentAsync(StudentWcfConsume.ServiceReference1.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudent", ReplyAction="http://tempuri.org/IService1/DeleteStudentResponse")]
        void DeleteStudent(string cin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteStudent", ReplyAction="http://tempuri.org/IService1/DeleteStudentResponse")]
        System.Threading.Tasks.Task DeleteStudentAsync(string cin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudent", ReplyAction="http://tempuri.org/IService1/GetStudentResponse")]
        StudentWcfConsume.ServiceReference1.Student GetStudent(string cin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudent", ReplyAction="http://tempuri.org/IService1/GetStudentResponse")]
        System.Threading.Tasks.Task<StudentWcfConsume.ServiceReference1.Student> GetStudentAsync(string cin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFils", ReplyAction="http://tempuri.org/IService1/GetFilsResponse")]
        string[] GetFils();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetFils", ReplyAction="http://tempuri.org/IService1/GetFilsResponse")]
        System.Threading.Tasks.Task<string[]> GetFilsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentsByFil", ReplyAction="http://tempuri.org/IService1/GetStudentsByFilResponse")]
        StudentWcfConsume.ServiceReference1.Student[] GetStudentsByFil(string fil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStudentsByFil", ReplyAction="http://tempuri.org/IService1/GetStudentsByFilResponse")]
        System.Threading.Tasks.Task<StudentWcfConsume.ServiceReference1.Student[]> GetStudentsByFilAsync(string fil);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : StudentWcfConsume.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<StudentWcfConsume.ServiceReference1.IService1>, StudentWcfConsume.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StudentWcfConsume.ServiceReference1.Student[] GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<StudentWcfConsume.ServiceReference1.Student[]> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        public void CreateStudent(StudentWcfConsume.ServiceReference1.Student s) {
            base.Channel.CreateStudent(s);
        }
        
        public System.Threading.Tasks.Task CreateStudentAsync(StudentWcfConsume.ServiceReference1.Student s) {
            return base.Channel.CreateStudentAsync(s);
        }
        
        public void UpdateStudent(StudentWcfConsume.ServiceReference1.Student s) {
            base.Channel.UpdateStudent(s);
        }
        
        public System.Threading.Tasks.Task UpdateStudentAsync(StudentWcfConsume.ServiceReference1.Student s) {
            return base.Channel.UpdateStudentAsync(s);
        }
        
        public void DeleteStudent(string cin) {
            base.Channel.DeleteStudent(cin);
        }
        
        public System.Threading.Tasks.Task DeleteStudentAsync(string cin) {
            return base.Channel.DeleteStudentAsync(cin);
        }
        
        public StudentWcfConsume.ServiceReference1.Student GetStudent(string cin) {
            return base.Channel.GetStudent(cin);
        }
        
        public System.Threading.Tasks.Task<StudentWcfConsume.ServiceReference1.Student> GetStudentAsync(string cin) {
            return base.Channel.GetStudentAsync(cin);
        }
        
        public string[] GetFils() {
            return base.Channel.GetFils();
        }
        
        public System.Threading.Tasks.Task<string[]> GetFilsAsync() {
            return base.Channel.GetFilsAsync();
        }
        
        public StudentWcfConsume.ServiceReference1.Student[] GetStudentsByFil(string fil) {
            return base.Channel.GetStudentsByFil(fil);
        }
        
        public System.Threading.Tasks.Task<StudentWcfConsume.ServiceReference1.Student[]> GetStudentsByFilAsync(string fil) {
            return base.Channel.GetStudentsByFilAsync(fil);
        }
    }
}
